version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bookstore_local_django
    container_name: django
    depends_on:
      - db
    volumes:
      - .:/code
    env_file: ./.env/.local/.django
    ports:
      # HOST_PORT:CONTAINER_PORT
      - 8000:8000
    command: python /code/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:11
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env/.local/.postgres
    ports:
      - 5432

volumes:
  postgres_data:
