version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: sleep for launch db to migrate at Django
          command: sleep 10
      - run:
          name: migrate
          command: docker-compose run --rm django python manage.py migrate

  deploy: &deploy-heroku

    working_directory: ~/base_project

    docker:
      # Primary container image with stable versions of Docker and Git
      - image: docker:stable-git
    steps:
      - checkout

  deploy-staging:
    <<: *deploy-heroku

    environment:
      ENVIRONMENT: "staging"

    steps:
      - checkout
      - run:
          # Deployment to heroku staging environment
          name: Deploy to heroku development remote
          command: 
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP-$ENVIRONMENT.git $CIRCLE_BRANCH:master

  deploy-production:
    <<: *deploy-heroku

    environment:
      ENVIRONMENT: "production"

    steps:
      - checkout
      - run:
          # Deployment to heroku staging environment
          name: Deploy to heroku development remote
          command: 
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP-$ENVIRONMENT.git $CIRCLE_BRANCH:master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging

      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master

